### ISSUE TITLE
TypeError: Object #<Jenkins> has no method 'last'

### ISSUE THREAD

**Issue by catchharish** [cliffano/nestor#27]
Hello there,

I am stuck with a weird problem. While using nestor, I am unable to execute the method 'last' and I keep getting the error mentioned here..

TypeError: Object #<Jenkins> has no method 'last'

What may I be doing wrong here, or is it a bug of some sort with the nestor implementation I am attaching the code snippet here..

var nestor = new (require('nestor'))('credentials@jenkins_ip:8080');
nestor.last(jenkinsJobName,function(err, data){
})

**Comment by cliffano** [comment]
That is because nestor relies on the response code that Jenkins returns.
nestor will give 'success' as long Jenkins responds with 200 or 201
nestor will give 'failure' for 404, 405
nestor will give unexpected 'failure' for anything else

In your case, triggering the build job multiple times causes Jenkins to respond with a set of 200s, but the server itself might do something smart like knowing that the requests were sent within a short period of time. I'm just guessing here, you'll need to look at Jenkins code to figure out how it behaves, perhaps check out the Jenkins log for any clue.
