### ISSUE TITLE
Allow --console flag to be used with parameterized builds

### ISSUE THREAD

**Issue by erquhart** [cliffano/nestor#35]
All of our builds are parameterized, so we have to do:

```shell
nestor build <job> <params> && nestor console <job>
```

Have you considered allowing parameterized builds to just use the `--console` flag?

**Comment by thisgeek** [comment]
Did you try this?

```
nestor build <job> <params> --console
```

**Comment by erquhart** [comment]
Yep, that works.

**Comment by cliffano** [comment]
@thisgeek Thanks for that. I've updated the readme and help menu with that example https://github.com/cliffano/nestor/commit/ced7ccbd360599c888e6e24b27d59feb590dacea .

@erquhart What version of nestor and Jenkins are you using?
What command line did you use when it didn't work? And did you get any error message or no output?

From memory, `nestor build --console <job> <params>` used to work, so it could be changes in commander module ever since that made opt needs to be at the end if there's an optional command arg.

**Comment by cliffano** [comment]
Closing this issue for now since the original problem was solved.
Still interested to learn about the error message/output when the original problem occurred.
