### ISSUE TITLE
Build didn't start after 30 seconds

### ISSUE THREAD

**Issue by jasperrooduijn** [cliffano/nestor#54]
Nestor works great for me. Thanks for that. Except from the --console param. When i use it i always get the same feedback. It tells me 'Waiting for the job to start' and after 30 seconds 'Build didn't start after 30 seconds, it's still waiting in the queue'. Althought the job was started and finished succesfully. This is the same for al my  build tasks. I tried different ones.

**Console output:**

`nestor build 'projectname' --console`
`Job projectname was triggered successfully`
`Waiting for job to start...`
`Waiting for job to start...`
`Waiting for job to start...`
`Waiting for job to start...`
`Waiting for job to start...`
`Waiting for job to start...`
`Waiting for job to start...`
`Waiting for job to start...`
`Waiting for job to start...`
`Waiting for job to start...`
`Waiting for job to start...`
`Waiting for job to start...`
`Waiting for job to start...`
`Waiting for job to start...`
`Waiting for job to start...`
`Build didn't start after 30 seconds, it's still waiting in the queue`

**My actual versions are:**

`node --version -> v6.11.1`
`npm --version -> 3.10.10`
`nestor --version -> 1.0.2`
`nestor ver -> Jenkins ver. 2.103`

**Comment by cliffano** [comment]
@jasperrooduijn Thanks for reporting this issue, it was fixed in #46 , my apology for not releasing the fix earlier on.

I finally got around to publishing nestor v2.0.0 https://www.npmjs.com/package/nestor , please upgrade your nestor installation and please let me know if it works for you.

v2.0.0 uses a new jenkins api client called https://www.npmjs.com/package/swaggy-jenkins , so I would be interested to learn if it works with your Jenkins installation.

**Comment by jasperrooduijn** [comment]
@cliffano Thanks! Works great! The upgrade did the job. I did sime test builds with several projects, all seems to work fine with my version of Jenkins.

**Comment by cliffano** [comment]
@jasperrooduijn Thanks for the update. Will close this ticket, but please feel free to open new issue if you encountered any.
And thanks for using nestor, much appreciated.
